routes/web.php
<?php

declare(strict_types=1);

use Bittacora\Bpanel4\Slider\Http\Controllers\SlideAdminController;
use Bittacora\Bpanel4\Slider\Http\Controllers\SliderAdminController;
use Illuminate\Support\Facades\Route;

Route::prefix('bpanel/sliders')->name('bpanel4-slider.bpanel.')->middleware(['web', 'auth', 'admin-menu'])
    ->group(function (): void {
        Route::get('/', [SliderAdminController::class, 'index'])->name('index');
        Route::get('/nuevo', [SliderAdminController::class, 'create'])->name('create');
        Route::get('{model}/editar/{locale?}', [SliderAdminController::class, 'edit'])->name('edit');
        Route::get('/diapositiva/{slide}/quitar-fondo-movil', [SliderAdminController::class, 'removeMobileBackground'])
            ->name('remove-mobile-background');
        Route::post('/store', [SliderAdminController::class, 'store'])->name('store');
        Route::post('{slider}/actualizar', [SliderAdminController::class, 'update'])->name('update');
        Route::delete('{slider}/destroy', [SliderAdminController::class, 'destroy'])->name('destroy');
    });

Route::prefix('bpanel/sliders')->name('bpanel4-slider.bpanel.slide.')->middleware(['web', 'auth', 'admin-menu'])
    ->group(function (): void {
        Route::get('/{slider}/nueva-diapositiva/{locale?}', [SlideAdminController::class, 'create'])->name('create');
        Route::get('/{model}/editar-diapositiva/{locale?}', [SlideAdminController::class, 'edit'])->name('edit');
        Route::post('/{slider}/store-slide', [SlideAdminController::class, 'store'])->name('store');
        Route::post('/{slide}/actualizar-diapositiva/{locale?}', [SlideAdminController::class, 'update'])->name('update');
        Route::delete('/{slide}/destroy-slide', [SlideAdminController::class, 'destroy'])->name('destroy');
    });

resources/views/bpanel/_form.blade.php
<form class="mt-lg-3" autocomplete="off" method="post" action="{{ $action }}" enctype="multipart/form-data">
    @csrf
    @livewire('form::input-text', ['name' => 'title', 'labelText' => __('bpanel4-slider::form.title'), 'required'=>true,
    'value' => old('title') ?? $slider?->getTitle() ])
    @livewire('form::input-number', ['name' => 'slide_duration', 'labelText' =>
    __('bpanel4-slider::form.slide_duration'), 'min' => 0, 'required'=>true, 'value' => old('slide_duration') ??
    $slider?->getSlideDuration() ?? 3000, 'labelWidth' => 3, 'fieldWidth' => 7 ])
    @livewire('form::input-number', ['name' => 'mobile_breakpoint', 'labelText' =>
    __('bpanel4-slider::form.mobile_breakpoint'), 'min' => 0, 'required'=>true, 'value' => old('mobile_breakpoint') ??
    $slider?->getMobileBreakpoint() ?? 640, 'labelWidth' => 3, 'fieldWidth' => 7 ])
    @livewire('form::select', ['name' => 'effect', 'selectedValues' => [$slider?->getEffect()], 'allValues' => [
    'slide' => 'Deslizar',
    'fade' => 'Fundir',
    'cube' => 'Cubo',
    'coverflow' => 'Coverflow',
    'flip' => 'Voltear',
    'creative' => 'Creativo'
    ], 'labelText' => __('bpanel4-slider::form.effect'), 'fieldWidth' => 7])
    @livewire('form::input-checkbox', ['name' => 'show_pagination', 'value' => 1, 'checked' => old('show_pagination') ??
    $slider?->showPagination(), 'labelText' => __('bpanel4-slider::form.show_pagination'), 'bpanelForm' => true])
    @livewire('form::input-checkbox', ['name' => 'show_arrows', 'value' => 1, 'checked' => old('show_arrows') ??
    $slider?->showarrows(), 'labelText' => __('bpanel4-slider::form.show_arrows'), 'bpanelForm' => true])
    @livewire('form::input-checkbox', ['name' => 'active', 'value' => 1, 'checked' => old('active') ??
    $slider?->isActive(), 'labelText' => __('bpanel4-slider::form.active'), 'bpanelForm' => true])
    <div class="col-12 mt-5 border-t-1 bgc-secondary-l4 brc-secondary-l2 py-35 d-flex justify-content-center">
        @livewire('form::save-button',['theme'=>'save'])
        @livewire('form::save-button',['theme'=>'update'])
        @livewire('form::save-button',['theme'=>'reset'])
    </div>
    @if($slider?->getId() !== null)
        <input type="hidden" name="id" value="{{ $slider->getId() }}">
    @endif

    @if(isset($language))
        <input type="hidden" name="locale" value="{{ $language }}">
    @endif
</form>

resources/views/bpanel/create.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', __('bpanel4-slider::form.new'))

@section('content')
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('bpanel4-slider::form.new') }}</span>
            </h4>
        </div>
        @include('bpanel4-slider::bpanel._form', ['panelTitle' => __('bpanel4-slider::form.new')])
    </div>

    <div class="mt-4 text-center">
        <a href="{{ route('bpanel4-slider.bpanel.index') }}">< Volver al listado</a>
    </div>
@endsection

resources/views/bpanel/edit.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', __('bpanel4-slider::form.edit'))

@section('content')
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('bpanel4-slider::form.edit') }}</span>
            </h4>
        </div>

            <p></p>
        <div class="text-center mb-4 alert alert-primary font-bold mx-4">
            <i class="far fa-info-circle"></i> Para insertar este slider, pegue el siguiente código en una página, blog, etc: &#91;bpanel4-slider id={{ $slider->getId() }}&#93;&#91;/bpanel4-slider&#93;
        </div>
        @include('bpanel4-slider::bpanel._form', ['panelTitle' => __('bpanel4-slider::form.edit')])
    </div>

    <div class="card bcard mt-5">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('bpanel4-slider::form.edit-slides') }}</span>
            </h4>
        </div>
        <div class="p-4">
            @livewire('bpanel4-slider::slides-datatable', ['slider' => $slider])
            <div class="mt-3 text-right">
                <a href="{{ route('bpanel4-slider.bpanel.slide.create', ['slider' => $slider->getId()]) }}">
                    <button class="btn btn-success"><i class="fas fa-plus"></i> Añadir diapositiva</button>
                </a>
            </div>
        </div>
    </div>

    <div class="mt-4 text-center">
        <a href="{{ route('bpanel4-slider.bpanel.index') }}">< Volver al listado</a>
    </div>
@endsection

@push('scripts')
    @vite('vendor/bittacora/bpanel4-panel/resources/assets/js/livewire-sortable.js')
@endpush

resources/views/bpanel/index.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', 'Sliders')

@section('content')
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('bpanel4-slider::datatable.index') }}</span>
            </h4>
        </div>
        <div class="card-body">
            @livewire('bpanel4-slider::slider-datatable', [], key('bpanel4-slider-datatable'))
        </div>
    </div>

@endsection

resources/views/bpanel/livewire/datatable-fields/slide-actions.blade.php
@livewire('utils::datatable-action-buttons', ['actions' => ["edit", "delete"], 'scope' => 'bpanel4-slider.bpanel.slide', 'model' => $row, 'permission' => ['edit', 'delete'], 'id' => $row->id, 'message' => 'la diapositiva?'], key('user-buttons-'.$row->id))

resources/views/bpanel/livewire/datatable-fields/slide-active.blade.php
@livewire('utils::datatable-default', ['fieldName' => 'active', 'model' => $row, 'value' => $row->active, 'size' => 'xxs'], key('active-user-'.$row->id))

resources/views/bpanel/livewire/datatable-fields/slide-languages.blade.php
@livewire('language::datatable-languages', ['model' => $row, 'createRouteName' => 'bpanel4-slider.bpanel.slide.edit', 'editRouteName' => 'bpanel4-slider.bpanel.slide.edit',
], key('languages-blog-'.$row->id))

resources/views/bpanel/livewire/datatable-fields/slider-actions.blade.php
@livewire('utils::datatable-action-buttons', ['actions' => ["edit", "delete"], 'scope' => 'bpanel4-slider.bpanel', 'model' => $row, 'permission' => ['edit', 'delete'], 'id' => $row->id, 'message' => 'el slider?'], key('user-buttons-'.$row->id))

resources/views/bpanel/livewire/datatable-fields/slider-active.blade.php
@livewire('utils::datatable-default', ['fieldName' => 'active', 'model' => $row, 'value' => $row->active, 'size' => 'xxs'], key('active-user-'.$row->id))

resources/views/bpanel/livewire/slider-datatable.blade.php
<td>
    {{ $row->title }}
</td>
<td>
    {{ $row->slides->count() }}
</td>
<td class="align-middle">
    @livewire('utils::datatable-default', ['fieldName' => 'active', 'model' => $row, 'value' => $row->active, 'size' => 'xxs'], key('active-user-'.$row->id))
</td>
<td class="align-middle">
    <div class="text-center">
        @livewire('utils::datatable-action-buttons', ['actions' => ["edit", "delete"], 'scope' => 'bpanel4-slider.bpanel', 'model' => $row, 'permission' => ['edit', 'delete'], 'id' => $row->id, 'message' => 'el slider?'], key('user-buttons-'.$row->id))
    </div>
</td>

resources/views/bpanel/livewire/slides-datatable.blade.php
<td>
    {{ $row->title }}
</td>
<td class="align-middle">
    @livewire('utils::datatable-default', ['fieldName' => 'active', 'model' => $row, 'value' => $row->active, 'size' => 'xxs'], key('active-user-'.$row->id))
</td>
<td>
    @livewire('language::datatable-languages', ['model' => $row, 'createRouteName' => 'bpanel4-slider.bpanel.slide.edit', 'editRouteName' => 'bpanel4-slider.bpanel.slide.edit',
    ], key('languages-blog-'.$row->id))
</td>
<td class="align-middle">
    <div class="text-center">
        @livewire('utils::datatable-action-buttons', ['actions' => ["edit", "delete"], 'scope' => 'bpanel4-slider.bpanel.slide', 'model' => $row, 'permission' => ['edit', 'delete'], 'id' => $row->id, 'message' => 'la diapositiva?'], key('user-buttons-'.$row->id))
    </div>
</td>

resources/views/bpanel/slides/_form.blade.php
<form class="mt-lg-3" autocomplete="off" method="post" action="{{ $action }}" enctype="multipart/form-data">
    @csrf
    @livewire('form::input-text', ['name' => 'title', 'labelText' => __('bpanel4-slider::form.title'), 'required'=>true,
    'value' => old('title') ?? $slide?->getTitle() ])
    @livewire('utils::tinymce-editor', ['name' => 'content', 'labelText' => __('bpanel4-slider::form.content'), 'value'
    => old('content') ?? $slide?->getContent() ])
    @if (null !== $slide?->getBackground())
        <div class="form-group form-row">
            <div class="col-sm-3 col-form-label text-sm-right">
                <label for="id-form-field-1" class="mb-0  ">
                    Fondo actual
                </label>
            </div>

            <div class="col-sm-7">
                <img src="{{ $slide->getBackground()->getFullUrl() }}" style="max-width: 500px;">
            </div>
        </div>
    @endif
    @livewire('form::input-file', ['name' => 'background', 'labelText' => 'Fondo',
    'maxFileCount' => 1, 'accept' => '.jpg,.jpeg,.png,.webp', 'allowedFileExtensions' => 'jpg,jpeg,png,webp' ])
    @if (null !== $slide?->getMobileBackground())
        <div class="form-group form-row">
            <div class="col-sm-3 col-form-label text-sm-right">
                <label for="id-form-field-1" class="mb-0  ">
                    Fondo actual (móviles)
                </label>
            </div>

            <div class="col-sm-7">
                <img src="{{ $slide->getMobileBackground()->getFullUrl() }}" style="max-width: 500px;">
                <div class="mt-2">
                    <a onclick="return confirm('¿Confirma que desea quitar la imagen?')" href="{{ route('bpanel4-slider.bpanel.remove-mobile-background', ['slide' => $slide]) }}" class="btn btn-danger"><i class="fas fa-times"></i> Quitar</a>
                </div>
            </div>
        </div>
    @endif
    @livewire('form::input-file', ['name' => 'mobile_background', 'labelText' => 'Fondo (dispositivos móviles)',
    'maxFileCount' => 1, 'accept' => '.jpg,.jpeg,.png,.webp', 'allowedFileExtensions' => 'jpg,jpeg,png,webp' ])
    {{ Bp4Hook::execute('slide-additional-fields', $slide) }}
    @livewire('form::input-text', ['name' => 'link', 'labelText' => __('bpanel4-slider::form.link'),
    'value' => old('link') ?? $slide?->getLink() ])
    @livewire('form::input-checkbox', ['name' => 'new_tab', 'value' => 1, 'checked' => old('new_tab') ??
    $slide?->getNewTab(), 'labelText' => __('bpanel4-slider::form.new_tab'), 'bpanelForm' => true])
    @livewire('form::input-checkbox', ['name' => 'active', 'value' => 1, 'checked' => old('active') ??
    $slide?->isActive(), 'labelText' => __('bpanel4-slider::form.active'), 'bpanelForm' => true])
    <div class="col-12 mt-5 border-t-1 bgc-secondary-l4 brc-secondary-l2 py-35 d-flex justify-content-center">
        @livewire('form::save-button',['theme'=>'save'])
        @livewire('form::save-button',['theme'=>'update'])
        @livewire('form::save-button',['theme'=>'reset'])
    </div>
    @if($slide?->getId() !== null)
        <input type="hidden" name="id" value="{{ $slide->getId() }}">
    @endif
    <input type="hidden" name="slider_id" value="{{ $slider->getId() }}">

    @if(isset($language))
        <input type="hidden" name="locale" value="{{ $language }}">
    @endif
</form>

resources/views/bpanel/slides/edit.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', __('bpanel4-slider::form.edit-slide'))

@section('content')
    @if(null === $slide)
        <p class="alert alert-success">
            {!!  __('bpanel4-slider::form.default_language') !!}
        </p>
    @endif
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('bpanel4-slider::form.edit-slide') }}</span>
            </h4>
            @if(null !== $slide)
                @include('language::partials.form-languages', ['model' => $slide, 'edit_route_name' => 'bpanel4-slider.bpanel.slide.edit',  'currentLanguage' => $language])
            @endif
        </div>
        @include('bpanel4-slider::bpanel.slides._form', ['panelTitle' => __('bpanel4-slider::form.edit-slide')])
    </div>
    <div class="mt-4 text-center">
        <a href="{{ route('bpanel4-slider.bpanel.edit', ['model' => $slider->id]) }}">< Volver al slider</a>
    </div>
@endsection

resources/views/shortcodes/slider.blade.php
@php
    /**
     * @var \Bittacora\Bpanel4\Slider\Models\Slider $slider
     * @var \Bittacora\Bpanel4\Slider\Models\Slide $slide
     */
@endphp
<div id="swiper-slider-{{ $slider->getId() }}" class="swiper swiper-slider swiper-slider-{{ $sliderKey }}" data-swiper-configuration="{{ json_encode([
   'pagination'  => $slider->showPagination() ? ['el' => '.swiper-pagination', 'clickable' => true] : false,
   'delay' => $slider->getSlideDuration(),
   'autoplay' => [ 'delay' => $slider->getSlideDuration(), 'disableOnInteraction' => false, ],
   'navigation' => $slider->showArrows() ? [
      'prevEl' => '.swiper-button-prev',
      'nextEl' => '.swiper-button-next'
    ]  : false,
    'effect' => $slider->getEffect(),
]) }}">
    <div class="swiper-wrapper">
        @foreach($slider->slides()->where('active', true)->get()->all() as $slide)
            <div class="swiper-slide @if(null !== $slide->getMobileBackground()) has-mobile-background @endif">
                @if(null !== $slide->getBackground())
                    <img class="desktop-background" src="{{ $slide->getBackground()->getFullUrl() }}" alt="Diapositiva {{ $slider->getId() }}">
                @endif
                @if(null !== $slide->getMobileBackground())
                    <img class="mobile-background" src="{{ $slide->getMobileBackground()->getFullUrl() }}" alt="Diapositiva {{ $slider->getId() }}">
                @endif
                <div class="content-wrapper">
                    <div class="content">
                        {!! $slide->getContent() !!}
                    </div>
                </div>
                {{ Bp4Hook::execute('show-slide-additional-fields', $slide) }}
            </div>
        @endforeach
    </div>
    @if($slider->showArrows())
        <div class="swiper-button-prev"></div>
        <div class="swiper-button-next"></div>
    @endif
    @if($slider->showPagination())
        <div class="swiper-pagination"></div>
    @endif
</div>

<style>
    .swiper-slider-{{ $sliderKey }} .desktop-background,
    .swiper-slider-{{ $sliderKey }} .mobile-background {
        width: 100%;
        height: auto;
        object-fit: cover;
        object-position: center center;
    }

    .swiper-slider-{{ $sliderKey }} .content-wrapper {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
    }

    @media (max-width: {{ $slider->getMobileBreakpoint() - 1 }}px) {
        .swiper-slider-{{ $sliderKey }} .mobile-background {
            display: block;
        }

        .swiper-slider-{{ $sliderKey }} .desktop-background {
            display: none;
        }
    }

    @media (min-width: {{ $slider->getMobileBreakpoint()}}px) {
        .swiper-slider-{{ $sliderKey }} .mobile-background {
            display: none;
        }

        .swiper-slider-{{ $sliderKey }} .desktop-background {
            display: block;
        }
    }
</style>